### ISSUE TITLE
License copyright owner "Democratized Data (D2) Foundation."

### ISSUE THREAD

**Issue by jsimnz** [sourcenetwork/defradb-client-py#7]
It current says "D2 Foundation", needs to be "Democratized Data (D2) Foundation"

**Comment by orpheuslummis** [comment]
then DefraDB's BSL license perhaps also need to be changed https://github.com/sourcenetwork/defradb/blob/develop/licenses/BSL.txt is also 

I took it from 

```
Licensor:                   Democratized Data (D2) Foundation

Licensed Work:              DefraDB v0.5.0
                            The Licensed Work is (c) 2023 D2 Foundation.
```

**Comment by orpheuslummis** [comment]
closed by https://github.com/sourcenetwork/defradb-client-py/commit/fdf46d6b87bde016b724d5dd59ce92a072fcb271

**Comment by jsimnz** [comment]
The defra BSL is fine. The `licensor` line defines D2 as an abbreviation for Democratized Data within that document. So the copy right line is actually referring to Democratized Data through the abbreviation.

In th is repos MIT license, there is no such abbreviation established.
